# Generated by Django 4.2.1 on 2023-05-09 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('status_friends', models.CharField(choices=[('Friend', 'Друг'), ('No friends', 'Не в друзьях')], max_length=50)),
                ('status_followers', models.CharField(choices=[('Outgoing request', 'Исходящая заявка'), ('Incoming request', 'Входящая заявка')], max_length=50)),
                ('followers', models.ManyToManyField(related_name='incoming_requests', through='api.Followers', to='api.profile', verbose_name='Заявки')),
                ('friends', models.ManyToManyField(related_name='comrades', through='api.Friends', to='api.profile', verbose_name='Друзья')),
            ],
        ),
        migrations.AddField(
            model_name='friends',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='api.profile'),
        ),
        migrations.AddField(
            model_name='friends',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='api.profile'),
        ),
        migrations.AddField(
            model_name='followers',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='api.profile'),
        ),
        migrations.AddField(
            model_name='followers',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='api.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='friends',
            unique_together={('person', 'friend')},
        ),
        migrations.AlterUniqueTogether(
            name='followers',
            unique_together={('follower', 'following')},
        ),
    ]
